# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: vPzBrig21.Arma3Sync
PackageVersion: 2026.4.15
PackageLocale: en-US
Publisher: Virtuelle Panzerbrigade 21 (vPzBrig21)
PublisherUrl: https://github.com/vpzbrig21/Arma3Sync
PublisherSupportUrl: https://github.com/vpzbrig21/Arma3Sync/issues
PackageName: Arma3Sync
PackageUrl: https://github.com/vpzbrig21/Arma3Sync
License: GPL-3.0-only
LicenseUrl: https://github.com/vpzbrig21/Arma3Sync/blob/v2026.4.15/LICENCE.md
ShortDescription: Cross-platform Arma 3 launcher and repository synchronizer.
Description: >-
  Arma3Sync is a cross-platform launcher and repository manager for Arma 3.
  It synchronizes addons, manages profiles and modsets, and supports FTP,
  SFTP, HTTP, HTTPS and WebDAV repositories.
ReleaseNotesUrl: https://github.com/vpzbrig21/Arma3Sync/releases/tag/v2026.4.15
Tags:
  - arma
  - arma3
  - launcher
  - mods
  - synchronizer

ManifestType: defaultLocale
ManifestVersion: 1.28.0
