# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: vPzBrig21.Arma3Sync
PackageVersion: 2026.4.15

Installers:
  - Architecture: x64
    Scope: machine
    InstallerType: nullsoft
    InstallerUrl: https://github.com/vpzbrig21/Arma3Sync/releases/download/v2026.4.15/Arma3Sync-2026.4.15-setup.exe
    InstallerSha256: 1411FF389FFEAE14B47439F46167ABBC67B264A931A3A1BF39BEDD5D4BDB8C9D
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    UpgradeBehavior: install
    ElevationRequirement: elevationRequired

ManifestType: installer
ManifestVersion: 1.28.0
