# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: vPzBrig21.Arma3Sync
PackageVersion: 2026.4.13

Installers:
  - Architecture: x64
    Scope: machine
    InstallerType: nullsoft
    InstallerUrl: https://github.com/vpzbrig21/Arma3Sync/releases/download/v2026.4.13/Arma3Sync-2026.4.13-setup.exe
    InstallerSha256: 8689A00C08E483E9097E72871AC111265E0768F958B7D30AD0BB1FE0F150616C
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    UpgradeBehavior: install
    ElevationRequirement: elevationRequired

ManifestType: installer
ManifestVersion: 1.28.0
